### ISSUE TITLE
example of how to build keyboard, etc 

### ISSUE THREAD

**Issue by doofin** [OueslatiGhaith/bluetooth-hci#10]
Hi, it's great to see this library? Are there any examples of how to use this for BLE GATT keyboard? thanks

**Comment by OueslatiGhaith** [comment]
Hi @doofin, I'm not really familiar with how keyboards work, so I can't be of any help here, but I can tell you that this library is built to work mainly with [Embassy](https://github.com/embassy-rs/embassy), you can find examples of how to use this library there.
