### ISSUE TITLE
Potential semver-breaking change in v0.17.1

### ISSUE THREAD

**Issue by jamesmunns** [OueslatiGhaith/bluetooth-hci#8]
Hey there, the recent 0.17.1 release seems to have broken embassy's CI, potentially indicating a semver breaking change:

https://ci.embassy.dev/jobs/4893f90b18df

```
   Compiling embassy-stm32wba-examples v0.1.0 (/ci/code/examples/stm32wba)
error: expected `const`
    --> /ci/cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/stm32wb-hci-0.17.1/src/vendor/command/gatt.rs:1863:9
     |
1863 |         WRITE_NO_RESP = 0x04;
     |         ^^^^^^^^^^^^^

error[E0412]: cannot find type `AccessPermission` in this scope
   --> /ci/cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/stm32wb-hci-0.17.1/src/vendor/command/gatt.rs:818:22
    |
818 |         permissions: AccessPermission,
    |                      ^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `AccessPermission` in this scope
    --> /ci/cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/stm32wb-hci-0.17.1/src/vendor/command/gatt.rs:1249:22
     |
1249 |         permissions: AccessPermission,
     |                      ^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `AccessPermission` in this scope
    --> /ci/cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/stm32wb-hci-0.17.1/src/vendor/command/gatt.rs:1731:29
     |
1731 |     pub access_permissions: AccessPermission,
     |                             ^^^^^^^^^^^^^^^^ not found in this scope
```

Just letting you know this occurred.

**Comment by jamesmunns** [comment]
I can't spot the issue in https://github.com/OueslatiGhaith/stm32wb-hci/compare/v0.17.0...v0.17.1, though it's potentially due to use of wildcard imports.

**Comment by jamesmunns** [comment]
Ah, this appears to be a syntax bug, at least:

https://github.com/OueslatiGhaith/stm32wb-hci/compare/v0.17.0...v0.17.1#diff-cdc589d1a7397443db4f5b998756d6bde279542747da2f6ab136574a3c09d0a5R1862-R1863

**Comment by OueslatiGhaith** [comment]
Hello @jamesmunns , 
Thank you for pointing that out, that seems to be a syntax issue that slipped through CI (though it is 100% my fault for not testing the `defmt` feature, I will add that to CI in the future). 
This should be fixed in [027016c](https://github.com/OueslatiGhaith/stm32wb-hci/commit/027016c603a0e9a31c04c20ff19cc3612022f311), I'll yank the affected version and publish a new one

**Comment by OueslatiGhaith** [comment]
new version [v0.17.2](https://crates.io/crates/stm32wb-hci/0.17.2) that solves this published. Closing.

**Comment by jamesmunns** [comment]
Thank you for the fast turnaround @OueslatiGhaith!
